import Header from "@/components/Header";
import { ReduxProvider } from "@/globalredux/ReduxProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { ClientThemeProvider } from "../theme/ThemeProvider";
import "../theme/css/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body className="bg-neutral-50">
        <ClientThemeProvider>
          <ReduxProvider>
            <Header />
            {children}
          </ReduxProvider>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
